### ISSUE TITLE
Swift package manager cannot resolve

### ISSUE THREAD

**Issue by emanuelef** [faberNovel/ADUtils#22]
Hi,
I'm trying to integrate the library using SPM, I'm getting an error when resolving.
![Screenshot 2021-05-13 at 09 56 00](https://user-images.githubusercontent.com/48717/118103093-6d67fb80-b3d1-11eb-86e6-fa9c339c0e4e.png)
I tried in my fork (https://github.com/emanuelef/ADUtils) and one fix that worked for me is to change the release version to 11.1.0, without the "v" prefix.
Not sure if there are ways to make SPM work with the v prefix, might be there's something I'm missing.
Thanks

**Comment by alexandre-pod** [comment]
Hi, there is still no release available with SPM, the last version available right now (v11.1.0) does not contain the `Package.swift` file, this explain the error message. 
If you want to use ADUtils right now you can say that you want to follow the `develop` branch, we need to release a new version to make it available on SPM using version number.

PS: the "v" prefix is not problematic, your fork worked because you created a tag on a commit containing the Package.swift file
